### ISSUE TITLE
Insufficient balance. Your available balance is: NaN MIA

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-wallet-web#1624]
What does this error mean? 
"Insufficient balance. Your available balance is: NaN MIA" even though balance is positive

I have seen this report from two users.

**Comment by markmhendrickson** [comment]
This appears fixed by https://github.com/blockstack/stacks-wallet-web/pull/1619

**Comment by Rapha-btc** [comment]
I still see the same error message though. Do I need to update the Hiro Wallet extension in Brave?

**Comment by markmhendrickson** [comment]
I believe Chrome (aka for Brave as well) has yet to approve the latest version with this fix (2.15.1) whereas Firefox has approved it.
